# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cont2discdlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_c2ddlg(object):
    def setupUi(self, c2ddlg):
        c2ddlg.setObjectName("c2ddlg")
        c2ddlg.resize(496, 367)
        c2ddlg.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(c2ddlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.numlabel = QtWidgets.QLabel(c2ddlg)
        self.numlabel.setText("")
        self.numlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numlabel.setObjectName("numlabel")
        self.verticalLayout.addWidget(self.numlabel)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.impuse_radio = QtWidgets.QRadioButton(c2ddlg)
        self.impuse_radio.setChecked(True)
        self.impuse_radio.setObjectName("impuse_radio")
        self.verticalLayout_2.addWidget(self.impuse_radio)
        self.step_radio = QtWidgets.QRadioButton(c2ddlg)
        self.step_radio.setObjectName("step_radio")
        self.verticalLayout_2.addWidget(self.step_radio)
        self.custom_radio = QtWidgets.QRadioButton(c2ddlg)
        self.custom_radio.setObjectName("custom_radio")
        self.verticalLayout_2.addWidget(self.custom_radio)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadfile = QtWidgets.QPushButton(c2ddlg)
        self.loadfile.setEnabled(False)
        self.loadfile.setObjectName("loadfile")
        self.horizontalLayout_2.addWidget(self.loadfile)
        self.sampletime_label = QtWidgets.QLabel(c2ddlg)
        self.sampletime_label.setEnabled(False)
        self.sampletime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sampletime_label.setObjectName("sampletime_label")
        self.horizontalLayout_2.addWidget(self.sampletime_label)
        self.ts_edit = QtWidgets.QLineEdit(c2ddlg)
        self.ts_edit.setEnabled(False)
        self.ts_edit.setObjectName("ts_edit")
        self.horizontalLayout_2.addWidget(self.ts_edit)
        self.sec_label = QtWidgets.QLabel(c2ddlg)
        self.sec_label.setEnabled(False)
        self.sec_label.setObjectName("sec_label")
        self.horizontalLayout_2.addWidget(self.sec_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.method_label = QtWidgets.QLabel(c2ddlg)
        self.method_label.setEnabled(False)
        self.method_label.setAlignment(QtCore.Qt.AlignCenter)
        self.method_label.setObjectName("method_label")
        self.horizontalLayout_3.addWidget(self.method_label)
        self.methodbox = QtWidgets.QComboBox(c2ddlg)
        self.methodbox.setEnabled(False)
        self.methodbox.setObjectName("methodbox")
        self.methodbox.addItem("")
        self.methodbox.addItem("")
        self.horizontalLayout_3.addWidget(self.methodbox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(c2ddlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(c2ddlg)
        self.buttonBox.accepted.connect(c2ddlg.accept)
        self.buttonBox.rejected.connect(c2ddlg.reject)
        QtCore.QMetaObject.connectSlotsByName(c2ddlg)

    def retranslateUi(self, c2ddlg):
        _translate = QtCore.QCoreApplication.translate
        c2ddlg.setWindowTitle(_translate("c2ddlg", "c2d table"))
        self.impuse_radio.setText(_translate("c2ddlg", "impuse"))
        self.step_radio.setText(_translate("c2ddlg", "Step"))
        self.custom_radio.setText(_translate("c2ddlg", "custom signal"))
        self.loadfile.setText(_translate("c2ddlg", "Load data"))
        self.sampletime_label.setText(_translate("c2ddlg", "Sample Time"))
        self.sec_label.setText(_translate("c2ddlg", "Sec"))
        self.method_label.setText(_translate("c2ddlg", "Method"))
        self.methodbox.setItemText(0, _translate("c2ddlg", "Zero order hoh"))
        self.methodbox.setItemText(1, _translate("c2ddlg", "bilinear"))

